# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  clean:
    executor:
      name: node/default
      tag: '12.18'
    steps:
      - run: rm -rf build

  build:
    executor:
      name: node/default
      tag: '12.18'
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: yarn start

workflows:
  version: 2
  main:
    jobs:
      - clean
      - build:
          requires:
            - clean
